env:
  es6: true
  node: true
  mocha: true
extends: eslint:recommended
parserOptions:
  sourceType: module
  ecmaVersion: 8
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  arrow-parens:
    - error
    - as-needed
  arrow-spacing: error
  complexity:
    - error
    - 10
  consistent-return: warn
  curly: error
  no-cond-assign: 'off'
  no-duplicate-imports: error
  no-else-return: error
  no-extra-parens: error
  no-extra-semi: error
  no-loop-func: error
  no-proto: error
  no-return-await: error
  no-useless-constructor: error
  padded-blocks:
    - error
    - never
  space-before-function-paren:
    - error
    - anonymous: never
      named: never
      asyncArrow: always
